class AppTexts {
  static const String aboutPAA =
      'Pakistan Civil Aviation Authority (CAA) is a public sector autonomous body working under the Federal Government of Pakistan through Aviation Division Cabinet Secretariat. CAA was established on 7th December, 1982 through Pakistan Civil Aviation Authority ordinance 1982. Prior to creation of CAA, a Civil Aviation Department (CAD) in the Ministry of Defence (MoD) used to manage the Civil Aviation related activities. Ministry of Defence (MoD) continued to be the controlling Ministry even after creation of CAA on 7th December, 1982. However, in June, 2013, Government of Pakistan assigned this responsibility to Cabinet Secretariat (Aviation Division)\n\nThe purpose of establishing CAA is to provide for the promotion and regulations of Civil Aviation activities and to develop an infrastructure for safe, efficient, adequate, economical and properly coordinated Civil Air Transport Service in Pakistan.The day of 7th December has significance, as it coincides with the date of creation of International Civil Aviation Organization (ICAO) in 1944 as a result of the famous Chicago Convention.';
  static const String notice =
      'Below you can find travel guidelines for your origin and destination countries. If your requirement about the covid-19 PCR test is different between the departing and arriving countries, you should follow the requirement which is most restrictive.';
  static const String turkiye =
      'Carrying Areca Nuts (Chalia) is banned in Turkiye, and Passengers found with Areca Nuts falls under the nasrcotrics/ Drugs category in Turkiye, banned and a publishable crime. Therefore, passengers travelling to Turkiye are advised not to carry Areca Nuts in their own interest, while travelling to Turkiye, being illegal.';
  static const String senior =
      'We pride ourselves on making our airports and services accessible to passengers with restricted/reduced mobility and special needs. Facility is available for all privileged Special passengers and senior citizens. Facilities are signposted and identified with the standard International Sinology. Passenger with such needs should notify their airlines ahead of their visit. They can contact concerned airlines for wheel chair service on their special counters in Arrival and Departure Halls/Concourse Hall.\n\nFor the purpose we have Fast track for arriving/departing formalities, Elevators and smooth ramp for passenger using wheel chair, designated washrooms and specified parking for special persons are also available.';
  static const String news =
      'Carrying Areca Nuts (Chalia) is banned in Turkiye, and Passengers found with Areca Nuts falls under the nasrcotrics/ Drugs category in Turkiye, banned and a publishable crime. Therefore, passengers travelling to Turkiye are advised not to carry Areca Nuts in their own interest, while travelling to Turkiye, being illegal.';
  static const String grievance =
      'Grievance Commissioner Cell for Overseas Pakistanis in Federal Ombudsman Secretariat was established in 2015 under section (7) of the Federal Ombudsman Institutional Reforms Act, 2013, to address the individual and systematic issues of the overseas Pakistanis related to the Federal Government Ministries, Departments, Organizations and Agencies.\n\nThe detail information for contacting the Secretariat of Federal Ombudsman and Grievance Commissioner Cell is as follows :';
}
